import type { RouteObject } from 'react-router-dom';

/**
 * Screens ported from the Next.js prototype — GENERATED, do not hand-edit.
 * Regenerate with: node client/scripts/port-prototype.mjs
 *
 * Each route is code-split: React Router imports the module the first time the
 * route is visited, so 99 screens cost nothing until they are opened.
 *
 * These render the fixture dataset in src/lib/mock-data.ts. Routes backed by the
 * live API are declared in router.tsx and excluded from this list.
 */
export const prototypeRoutes: RouteObject[] = [
  { path: 'admin/api-keys', lazy: async () => ({ Component: (await import('@/pages/admin/api-keys/page')).default }) },
  { path: 'admin/billing', lazy: async () => ({ Component: (await import('@/pages/admin/billing/page')).default }) },
  { path: 'admin/branding', lazy: async () => ({ Component: (await import('@/pages/admin/branding/page')).default }) },
  { path: 'admin/data', lazy: async () => ({ Component: (await import('@/pages/admin/data/page')).default }) },
  { path: 'admin/facilities', lazy: async () => ({ Component: (await import('@/pages/admin/facilities/page')).default }) },
  { path: 'admin/facilities/:id', lazy: async () => ({ Component: (await import('@/pages/admin/facilities/[id]/page')).default }) },
  { path: 'admin/integrations', lazy: async () => ({ Component: (await import('@/pages/admin/integrations/page')).default }) },
  { path: 'admin/org', lazy: async () => ({ Component: (await import('@/pages/admin/org/page')).default }) },
  { path: 'admin/teams', lazy: async () => ({ Component: (await import('@/pages/admin/teams/page')).default }) },
  { path: 'admin/users/:id', lazy: async () => ({ Component: (await import('@/pages/admin/users/[id]/page')).default }) },
  { path: 'admin/webhooks', lazy: async () => ({ Component: (await import('@/pages/admin/webhooks/page')).default }) },
  { path: 'admin/workflows', lazy: async () => ({ Component: (await import('@/pages/admin/workflows/page')).default }) },
  { path: 'ai/anomaly', lazy: async () => ({ Component: (await import('@/pages/ai/anomaly/page')).default }) },
  { path: 'ai/explainability', lazy: async () => ({ Component: (await import('@/pages/ai/explainability/page')).default }) },
  { path: 'ai/feedback', lazy: async () => ({ Component: (await import('@/pages/ai/feedback/page')).default }) },
  { path: 'ai/forecasting', lazy: async () => ({ Component: (await import('@/pages/ai/forecasting/page')).default }) },
  { path: 'ai/health', lazy: async () => ({ Component: (await import('@/pages/ai/health/page')).default }) },
  { path: 'ai/models', lazy: async () => ({ Component: (await import('@/pages/ai/models/page')).default }) },
  { path: 'ai/models/:id', lazy: async () => ({ Component: (await import('@/pages/ai/models/[id]/page')).default }) },
  { path: 'ai/predictive', lazy: async () => ({ Component: (await import('@/pages/ai/predictive/page')).default }) },
  { path: 'ai/theft', lazy: async () => ({ Component: (await import('@/pages/ai/theft/page')).default }) },
  { path: 'ai/utilization', lazy: async () => ({ Component: (await import('@/pages/ai/utilization/page')).default }) },
  { path: 'alert-rules/new', lazy: async () => ({ Component: (await import('@/pages/alert-rules/new/page')).default }) },
  { path: 'alerts/:id', lazy: async () => ({ Component: (await import('@/pages/alerts/[id]/page')).default }) },
  { path: 'assets/:id/edit', lazy: async () => ({ Component: (await import('@/pages/assets/[id]/edit/page')).default }) },
  { path: 'assets/import', lazy: async () => ({ Component: (await import('@/pages/assets/import/page')).default }) },
  { path: 'assets/labels', lazy: async () => ({ Component: (await import('@/pages/assets/labels/page')).default }) },
  { path: 'audit', lazy: async () => ({ Component: (await import('@/pages/audit/page')).default }) },
  { path: 'bi', lazy: async () => ({ Component: (await import('@/pages/bi/page')).default }) },
  { path: 'certifications', lazy: async () => ({ Component: (await import('@/pages/certifications/page')).default }) },
  { path: 'checkinout', lazy: async () => ({ Component: (await import('@/pages/checkinout/page')).default }) },
  { path: 'checklists', lazy: async () => ({ Component: (await import('@/pages/checklists/page')).default }) },
  { path: 'compliance-reports', lazy: async () => ({ Component: (await import('@/pages/compliance-reports/page')).default }) },
  { path: 'consumption', lazy: async () => ({ Component: (await import('@/pages/consumption/page')).default }) },
  { path: 'copilot', lazy: async () => ({ Component: (await import('@/pages/copilot/page')).default }) },
  { path: 'custody/:assetId', lazy: async () => ({ Component: (await import('@/pages/custody/[assetId]/page')).default }) },
  { path: 'cycle-counts', lazy: async () => ({ Component: (await import('@/pages/cycle-counts/page')).default }) },
  { path: 'dashboards', lazy: async () => ({ Component: (await import('@/pages/dashboards/page')).default }) },
  { path: 'dashboards/ai', lazy: async () => ({ Component: (await import('@/pages/dashboards/ai/page')).default }) },
  { path: 'dashboards/asset', lazy: async () => ({ Component: (await import('@/pages/dashboards/asset/page')).default }) },
  { path: 'dashboards/executive', lazy: async () => ({ Component: (await import('@/pages/dashboards/executive/page')).default }) },
  { path: 'dashboards/financial', lazy: async () => ({ Component: (await import('@/pages/dashboards/financial/page')).default }) },
  { path: 'dashboards/inventory', lazy: async () => ({ Component: (await import('@/pages/dashboards/inventory/page')).default }) },
  { path: 'dashboards/maintenance', lazy: async () => ({ Component: (await import('@/pages/dashboards/maintenance/page')).default }) },
  { path: 'dashboards/operations', lazy: async () => ({ Component: (await import('@/pages/dashboards/operations/page')).default }) },
  { path: 'dashboards/security', lazy: async () => ({ Component: (await import('@/pages/dashboards/security/page')).default }) },
  { path: 'depreciation', lazy: async () => ({ Component: (await import('@/pages/depreciation/page')).default }) },
  { path: 'escalations', lazy: async () => ({ Component: (await import('@/pages/escalations/page')).default }) },
  { path: 'exports', lazy: async () => ({ Component: (await import('@/pages/exports/page')).default }) },
  { path: 'field-ops', lazy: async () => ({ Component: (await import('@/pages/field-ops/page')).default }) },
  { path: 'financials', lazy: async () => ({ Component: (await import('@/pages/financials/page')).default }) },
  { path: 'gateways/:id', lazy: async () => ({ Component: (await import('@/pages/gateways/[id]/page')).default }) },
  { path: 'geofences/new', lazy: async () => ({ Component: (await import('@/pages/geofences/new/page')).default }) },
  { path: 'groups', lazy: async () => ({ Component: (await import('@/pages/groups/page')).default }) },
  { path: 'groups/:id', lazy: async () => ({ Component: (await import('@/pages/groups/[id]/page')).default }) },
  { path: 'heatmaps', lazy: async () => ({ Component: (await import('@/pages/heatmaps/page')).default }) },
  { path: 'help', lazy: async () => ({ Component: (await import('@/pages/help/page')).default }) },
  { path: 'help/:article', lazy: async () => ({ Component: (await import('@/pages/help/[article]/page')).default }) },
  { path: 'inspections', lazy: async () => ({ Component: (await import('@/pages/inspections/page')).default }) },
  { path: 'inspections/:id', lazy: async () => ({ Component: (await import('@/pages/inspections/[id]/page')).default }) },
  { path: 'inventory/:sku', lazy: async () => ({ Component: (await import('@/pages/inventory/[sku]/page')).default }) },
  { path: 'kits', lazy: async () => ({ Component: (await import('@/pages/kits/page')).default }) },
  { path: 'lifecycle', lazy: async () => ({ Component: (await import('@/pages/lifecycle/page')).default }) },
  { path: 'maintenance/calendar', lazy: async () => ({ Component: (await import('@/pages/maintenance/calendar/page')).default }) },
  { path: 'movement', lazy: async () => ({ Component: (await import('@/pages/movement/page')).default }) },
  { path: 'movement/:assetId', lazy: async () => ({ Component: (await import('@/pages/movement/[assetId]/page')).default }) },
  { path: 'my-work', lazy: async () => ({ Component: (await import('@/pages/my-work/page')).default }) },
  { path: 'notifications/preferences', lazy: async () => ({ Component: (await import('@/pages/notifications/preferences/page')).default }) },
  { path: 'operations/transfers', lazy: async () => ({ Component: (await import('@/pages/operations/transfers/page')).default }) },
  { path: 'pm', lazy: async () => ({ Component: (await import('@/pages/pm/page')).default }) },
  { path: 'pm/:id', lazy: async () => ({ Component: (await import('@/pages/pm/[id]/page')).default }) },
  { path: 'predictive', lazy: async () => ({ Component: (await import('@/pages/predictive/page')).default }) },
  { path: 'procurement', lazy: async () => ({ Component: (await import('@/pages/procurement/page')).default }) },
  { path: 'procurement/:id', lazy: async () => ({ Component: (await import('@/pages/procurement/[id]/page')).default }) },
  { path: 'regulatory', lazy: async () => ({ Component: (await import('@/pages/regulatory/page')).default }) },
  { path: 'reorder', lazy: async () => ({ Component: (await import('@/pages/reorder/page')).default }) },
  { path: 'reports', lazy: async () => ({ Component: (await import('@/pages/reports/page')).default }) },
  { path: 'reports/:id', lazy: async () => ({ Component: (await import('@/pages/reports/[id]/page')).default }) },
  { path: 'reports/builder', lazy: async () => ({ Component: (await import('@/pages/reports/builder/page')).default }) },
  { path: 'reservations', lazy: async () => ({ Component: (await import('@/pages/reservations/page')).default }) },
  { path: 'retention', lazy: async () => ({ Component: (await import('@/pages/retention/page')).default }) },
  { path: 'scheduling', lazy: async () => ({ Component: (await import('@/pages/scheduling/page')).default }) },
  { path: 'sensors/:id', lazy: async () => ({ Component: (await import('@/pages/sensors/[id]/page')).default }) },
  { path: 'settings/api-tokens', lazy: async () => ({ Component: (await import('@/pages/settings/api-tokens/page')).default }) },
  { path: 'settings/appearance', lazy: async () => ({ Component: (await import('@/pages/settings/appearance/page')).default }) },
  { path: 'settings/notifications', lazy: async () => ({ Component: (await import('@/pages/settings/notifications/page')).default }) },
  { path: 'settings/profile', lazy: async () => ({ Component: (await import('@/pages/settings/profile/page')).default }) },
  { path: 'settings/security', lazy: async () => ({ Component: (await import('@/pages/settings/security/page')).default }) },
  { path: 'subscriptions', lazy: async () => ({ Component: (await import('@/pages/subscriptions/page')).default }) },
  { path: 'suppliers', lazy: async () => ({ Component: (await import('@/pages/suppliers/page')).default }) },
  { path: 'support', lazy: async () => ({ Component: (await import('@/pages/support/page')).default }) },
  { path: 'taxonomy', lazy: async () => ({ Component: (await import('@/pages/taxonomy/page')).default }) },
  { path: 'taxonomy/:class', lazy: async () => ({ Component: (await import('@/pages/taxonomy/[class]/page')).default }) },
  { path: 'telemetry', lazy: async () => ({ Component: (await import('@/pages/telemetry/page')).default }) },
  { path: 'twin', lazy: async () => ({ Component: (await import('@/pages/twin/page')).default }) },
  { path: 'twin/:facility', lazy: async () => ({ Component: (await import('@/pages/twin/[facility]/page')).default }) },
  { path: 'warehouses', lazy: async () => ({ Component: (await import('@/pages/warehouses/page')).default }) },
  { path: 'warehouses/:id', lazy: async () => ({ Component: (await import('@/pages/warehouses/[id]/page')).default }) },
  { path: 'whats-new', lazy: async () => ({ Component: (await import('@/pages/whats-new/page')).default }) },
];
