import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import globals from 'globals';

/**
 * One flat config for the whole workspace.
 *
 * The three packages share a language and a style, so they share a baseline;
 * only the genuinely environment-specific rules are split out — the browser
 * globals and React's hook rules apply to the frontend, Node's globals to the
 * backend, and neither belongs in the other.
 */
export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/node_modules/**',
      // Generated by scripts/, and regenerated rather than edited.
      'frontend/src/app/page-routes.ts',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    rules: {
      // An unused parameter is often meaningful (an Express error handler must
      // take four), so a leading underscore marks it deliberate.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
      // `any` defeats the point of the shared contract; the few places it is
      // genuinely needed carry an explicit disable comment saying why.
      '@typescript-eslint/no-explicit-any': 'error',
      'no-console': 'off',
      eqeqeq: ['error', 'smart'],
    },
  },

  // ── Frontend ───────────────────────────────────────────────────────────────
  {
    files: ['frontend/**/*.{ts,tsx}'],
    languageOptions: {
      globals: globals.browser,
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],
    },
  },

  // ── Backend ────────────────────────────────────────────────────────────────
  {
    files: ['backend/**/*.ts'],
    languageOptions: { globals: globals.node },
  },

  // ── Build scripts ──────────────────────────────────────────────────────────
  {
    files: ['scripts/**/*.mjs', '*.config.{ts,mjs}'],
    languageOptions: { globals: globals.node },
  },

  // ── QA harness ─────────────────────────────────────────────────────────────
  // Node scripts, but they also drive a browser: `cdp.mjs` uses the WebSocket
  // global that Node exposes under --experimental-websocket, and the runners
  // evaluate strings inside the page. Linted like any other source — the point
  // is to catch a typo in a test before it is mistaken for a product bug.
  {
    files: ['Testing/harness/**/*.mjs'],
    languageOptions: { globals: { ...globals.node, WebSocket: 'readonly' } },
  },
);
