// Regenerate the execution log and test-case register from the recorded runs.
//
//   node Testing/harness/report.mjs
//
// The markdown under Testing/ is generated, not hand-maintained, so re-running
// the suites and then this script keeps the documents honest. Hand-written
// analysis lives in 00-TEST-PLAN.md, 03-BUG-REPORTS.md and 04-SUMMARY.md.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';

const load = (f) => {
  const url = new URL(`../results/${f}`, import.meta.url);
  return existsSync(url) ? JSON.parse(readFileSync(url, 'utf8')) : null;
};

const api = load('api-results.json');
const ui = load('ui-results.json');
const reg = load('registration-results.json');
const regUi = load('registration-ui-results.json');
const runs = [
  ['API / Validation / Boundary / Security / Database', api],
  ['Add Asset flow (backend) — catalogue, templates, clone, registration', reg],
  ['Add Asset flow (browser) — source picker, sectioned form, template editor, clone', regUi],
  ['UI / UX / Accessibility / Responsive / Permission', ui],
].filter(([, r]) => r);

if (!runs.length) {
  console.error('No results found. Run the suites first.');
  process.exit(1);
}

const all = runs.flatMap(([, r]) => r.results);
const pass = all.filter((r) => r.status === 'PASS').length;
const fail = all.filter((r) => r.status === 'FAIL').length;
const pct = ((pass / all.length) * 100).toFixed(1);

const byType = {};
for (const r of all) {
  byType[r.type] ??= { total: 0, pass: 0 };
  byType[r.type].total++;
  if (r.status === 'PASS') byType[r.type].pass++;
}

const esc = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');

// ── Execution log ────────────────────────────────────────────────────────────

let log = `# Asset Management — Execution Log

**Module:** Asset Management  ·  **Build:** local dev (\`npm run dev\`)
**Environment:** Node 20.19.6 · Chrome 151 headless · MongoDB Atlas \`access_genie_demo\`
**Executed:** ${runs.map(([, r]) => new Date(r.ranAt).toISOString().replace('T', ' ').slice(0, 19)).join(' · ')} UTC

> Generated by \`Testing/harness/report.mjs\`. Do not edit by hand — re-run the
> suites and regenerate.

## Result

| | |
|---|---|
| **Executed** | ${all.length} |
| **Passed** | ${pass} |
| **Failed** | ${fail} |
| **Pass rate** | ${pct}% |

## By test type

| Type | Passed | Total | Rate |
|---|---:|---:|---:|
${Object.entries(byType).sort((a, b) => b[1].total - a[1].total)
  .map(([t, v]) => `| ${t} | ${v.pass} | ${v.total} | ${((v.pass / v.total) * 100).toFixed(0)}% |`).join('\n')}

`;

for (const [title, run] of runs) {
  log += `## ${title}\n\n`;
  log += `| Test ID | Feature | Type | Pri | Expected | Actual | Status | Sev |\n`;
  log += `|---|---|---|---|---|---|---|---|\n`;
  for (const r of run.results) {
    log += `| \`${r.id}\` | ${esc(r.feature)} | ${r.type} | ${r.priority} | ${esc(r.expected)} | ${esc(r.actual)} | ${r.status === 'PASS' ? '✅ PASS' : '❌ FAIL'} | ${r.severity} |\n`;
  }
  log += '\n';
  if (run.teardown) {
    log += `**Teardown:** removed ${run.teardown.removed.length} test assets`;
    log += run.teardown.stuck?.length ? `; **${run.teardown.stuck.length} could not be removed** — ${JSON.stringify(run.teardown.stuck)}\n\n` : ' — database returned to its pre-run state.\n\n';
  }
}

log += `## Failed cases\n\n`;
const failures = all.filter((r) => r.status === 'FAIL');
if (!failures.length) log += 'None.\n';
else {
  log += `| Test ID | Severity | Feature | Actual |\n|---|---|---|---|\n`;
  for (const r of failures) log += `| \`${r.id}\` | ${r.severity} | ${esc(r.feature)} | ${esc(r.actual)} |\n`;
}

writeFileSync(new URL('../02-EXECUTION-LOG.md', import.meta.url), log);

// ── Test-case register ───────────────────────────────────────────────────────

let register = `# Asset Management — Test Case Register

Every case below is **automated and executed** — none are aspirational. Source:
\`Testing/harness/api-tests.mjs\`, \`Testing/harness/registration-tests.mjs\`
and \`Testing/harness/ui-tests.mjs\`.

Reproduce the whole suite:

\`\`\`bash
node Testing/harness/api-tests.mjs
node Testing/harness/registration-tests.mjs
node --experimental-websocket Testing/harness/registration-ui-tests.mjs
node --experimental-websocket Testing/harness/ui-tests.mjs
node Testing/harness/report.mjs
\`\`\`

**Preconditions for every case:** the API is up on \`:4000\` with a connected
database, the web app on \`:5173\`, and the seeded super-admin exists
(\`npm run seed\`). Each runner authenticates itself and deletes everything it
creates.

| Test ID | Module | Feature | Type | Priority | Steps | Expected Result | Actual Result | Status | Severity |
|---|---|---|---|---|---|---|---|---|---|
`;

const steps = (r) => {
  if (r.id.startsWith('ARU-')) {
    return 'Sign in → open the add-asset step → wait for the data gate → assert on rendered DOM, console and the stored document';
  }
  if (r.id.startsWith('AR-')) {
    return 'Authenticate → call the registration/template endpoint → assert on status, envelope and the stored document';
  }
  if (r.id.startsWith('AM-UI') || r.id.startsWith('AM-UX') || r.id.startsWith('AM-A11Y') || r.id.startsWith('AM-RSP') || r.id.startsWith('AM-PERM') || r.id === 'AM-NEG-010' || r.id === 'AM-SEC-020' || r.id === 'AM-PERF-010') {
    return 'Sign in → navigate to the screen under test → wait for the data gate → assert on rendered DOM, console and network';
  }
  return 'Authenticate → issue the HTTP request described by the feature → assert on status code and response envelope';
};

for (const r of all) {
  register += `| \`${r.id}\` | Asset Management | ${esc(r.feature)} | ${r.type} | ${r.priority} | ${steps(r)} | ${esc(r.expected)} | ${esc(r.actual)} | ${r.status === 'PASS' ? '✅ PASS' : '❌ FAIL'} | ${r.severity} |\n`;
}

writeFileSync(new URL('../01-TEST-CASES.md', import.meta.url), register);

console.log(`Wrote 01-TEST-CASES.md and 02-EXECUTION-LOG.md`);
console.log(`${all.length} cases · ${pass} pass · ${fail} fail · ${pct}%`);
