// ─────────────────────────────────────────────────────────────────────────────
// Access Genie AI — Core domain types (demo / frontend-only slice)
// One asset graph: record + location + condition + prediction all on one object.
// ─────────────────────────────────────────────────────────────────────────────

export type AssetStatus = 'Active' | 'Maintenance' | 'Missing' | 'End_Of_Life' | 'Staging';
export type AssetHealth = 'Good' | 'Warning' | 'Critical';
export type AssetCategory = 'Compute' | 'Network' | 'Endpoints' | 'Infrastructure' | 'Sensors';
export type Criticality = 'Low' | 'Medium' | 'High' | 'Critical';

export interface Location {
  id: string;
  name: string;
  building?: string;
  floor?: string;
  zone?: string;
  coordinates?: { lat: number; lng: number };
}

export interface Telemetry {
  temperature?: number;
  humidity?: number;
  vibration?: number;
  batteryLevel?: number;
  lastPing: string;
}

/** A single point in a small time-series (used for sparklines / mini-charts). */
export interface TrendPoint {
  label: string;
  value: number;
}

export interface Asset {
  id: string;
  name: string;
  category: AssetCategory;
  serialNumber: string;
  status: AssetStatus;
  healthScore: number; // 0-100
  healthStatus: AssetHealth;
  location: Location;
  custodian: string;
  purchaseDate: string;
  purchasePrice: number;
  telemetry?: Telemetry;
  tags: string[];

  // ── Enriched fields (all optional so earlier records stay valid) ────────────
  manufacturer?: string;
  model?: string;
  criticality?: Criticality;
  riskScore?: number;         // 0-100 (higher = more at risk)
  utilization?: number;       // 0-100 (% of capacity used)
  bookValue?: number;         // depreciated value in USD
  depreciationMethod?: string;
  warrantyExpiry?: string;    // ISO date
  trackingTech?: string;      // e.g. "UWB", "BLE", "GPS"
  trackingId?: string;        // physical tag identifier (RFID EPC / BLE MAC / QR code / UWB anchor)
  lifecycleStage?: string;    // e.g. "In Service", "Commissioning", "EOL Planning"
  /** Position on the facility floor-plan SVG, as % (0-100) of width/height. */
  mapPosition?: { x: number; y: number };
  /** Recent health readings for the 360° sparkline. */
  healthTrend?: TrendPoint[];
}

// ── Maintenance / Work Orders ────────────────────────────────────────────────
export type WorkOrderStatus = 'New' | 'Assigned' | 'In Progress' | 'On Hold' | 'Completed';
export type WorkOrderPriority = 'Low' | 'Medium' | 'High' | 'Critical';
export type WorkOrderType = 'Preventive' | 'Corrective' | 'Predictive' | 'Inspection';

export interface WorkOrder {
  id: string;
  title: string;
  assetId: string;
  assetName: string;
  status: WorkOrderStatus;
  priority: WorkOrderPriority;
  type: WorkOrderType;
  assignedTo: string;
  createdAt: string;   // ISO
  dueDate: string;     // ISO
  description: string;
  estimatedHours: number;
  /** True when the WO was auto-generated by the AI predictive engine. */
  aiGenerated?: boolean;
}

// ── AI Intelligence ──────────────────────────────────────────────────────────
export type InsightType =
  | 'Predictive Failure'
  | 'Utilization'
  | 'Theft/Security'
  | 'Cost Optimization'
  | 'Anomaly'
  | 'Lifecycle';

export type InsightSeverity = 'Critical' | 'Warning' | 'Info' | 'Opportunity';

export interface AIInsight {
  id: string;
  type: InsightType;
  severity: InsightSeverity;
  title: string;
  summary: string;
  assetId?: string;
  assetName?: string;
  confidence: number;        // 0-100
  impactUsd?: number;        // $ impact if actioned (or avoided loss)
  impactLabel?: string;      // human label, e.g. "4 days to failure"
  /** Explainable-AI: the factors driving this score. */
  drivers: string[];
  recommendedAction: string;
  actionLabel: string;       // CTA button text
  createdAt: string;         // ISO
}

// ── Tracking / Live Map ──────────────────────────────────────────────────────
export type ZoneType = 'warehouse' | 'dock' | 'office' | 'restricted' | 'lab' | 'yard';

/** A rectangular zone on the facility floor-plan (coords are % of the SVG box). */
export interface MapZone {
  id: string;
  name: string;
  type: ZoneType;
  x: number;      // %
  y: number;      // %
  width: number;  // %
  height: number; // %
}

// ── Activity / Chain of custody ──────────────────────────────────────────────
export type ActivityType =
  | 'Movement'
  | 'Maintenance'
  | 'Custody'
  | 'Alert'
  | 'Registration'
  | 'Telemetry'
  | 'Audit';

export interface ActivityEvent {
  id: string;
  assetId: string;
  type: ActivityType;
  description: string;
  actor: string;
  timestamp: string; // ISO
}

// ── Aggregate chart series (for the executive dashboard) ─────────────────────
export interface UtilizationDowntimePoint {
  label: string;       // month
  utilization: number; // %
  downtime: number;    // hours
}

export interface CategoryBreakdown {
  category: AssetCategory;
  count: number;
  value: number; // USD
}

// ── Taxonomy & attribute schema (per-class dynamic attributes) ────────────────
export type AttributeType = 'text' | 'number' | 'select' | 'date' | 'boolean';
export interface AttributeDef {
  key: string;
  label: string;
  type: AttributeType;
  unit?: string;
  options?: string[];
  required?: boolean;
}
export interface TaxonomyClass {
  id: string;
  name: string;
  parentId?: string;
  icon: string;
  assetCount: number;
  attributes: AttributeDef[];
}

// ── Groups, fleets & kits ─────────────────────────────────────────────────────
export type GroupType = 'Group' | 'Fleet' | 'Kit';
export interface AssetGroup {
  id: string;
  name: string;
  type: GroupType;
  description: string;
  memberIds: string[];
}

// ── Documents / media attached to assets ─────────────────────────────────────
export type DocType = 'Manual' | 'Warranty' | 'Certificate' | 'Invoice' | 'Image' | 'CAD' | 'Report';
export interface AssetDoc {
  id: string;
  assetId: string;
  name: string;
  type: DocType;
  sizeKb: number;
  uploadedAt: string;
  uploadedBy: string;
}

// ── Tracking / IoT devices ────────────────────────────────────────────────────
export type SensorStatus = 'Online' | 'Offline' | 'Low Battery';
export type SensorKind = 'RFID Tag' | 'BLE Beacon' | 'UWB Tag' | 'GPS Tracker' | 'LoRaWAN Sensor' | 'Environmental';

export interface Sensor {
  id: string;
  name: string;
  kind: SensorKind;
  assetId?: string;
  assetName?: string;
  status: SensorStatus;
  batteryLevel?: number;   // 0-100
  signalStrength: number;  // 0-100
  firmwareVersion: string;
  gatewayId: string;
  zone?: string;
  lastReading: string;     // ISO
}

export type GatewayStatus = 'Online' | 'Degraded' | 'Offline';
export type GatewayKind = 'RFID Reader' | 'BLE Gateway' | 'LoRaWAN Gateway' | 'UWB Anchor';

export interface Gateway {
  id: string;
  name: string;
  kind: GatewayKind;
  status: GatewayStatus;
  connectedDevices: number;
  firmwareVersion: string;
  uptimePct: number;
  location: string;
  ip?: string;
  lastSeen: string;        // ISO
}

// ── Geofences & movement ──────────────────────────────────────────────────────
export type GeofenceRule = 'Entry' | 'Exit' | 'Dwell' | 'Restricted';
export interface Geofence {
  id: string;
  name: string;
  zoneId?: string;
  x: number; y: number; width: number; height: number; // percent of the 0-100 map box
  rule: GeofenceRule;
  breaches24h: number;
  active: boolean;
}

export interface TrailPoint {
  x: number; y: number; // percent
  timestamp: string;    // ISO
  label?: string;       // zone/waypoint
}
export interface MovementTrail {
  assetId: string;
  assetName: string;
  points: TrailPoint[];
  distanceM: number;
  dwellZones: { zone: string; minutes: number }[];
}

// ── Maintenance detail (per work order) ───────────────────────────────────────
export interface WoChecklistItem { label: string; done: boolean }
export interface WoPart { sku: string; name: string; qty: number; unitCost: number }
export interface WoLabor { tech: string; hours: number; note: string; at: string }
export interface WoComment { author: string; text: string; at: string }
export interface WorkOrderDetail {
  checklist: WoChecklistItem[];
  parts: WoPart[];
  laborLog: WoLabor[];
  comments: WoComment[];
}

export type PmFrequency = 'Monthly' | 'Quarterly' | 'Semi-Annual' | 'Annual' | 'Usage-based';
export interface PmSchedule {
  id: string;
  title: string;
  assetId: string;
  assetName: string;
  frequency: PmFrequency;
  type: WorkOrderType;
  nextDue: string;
  lastDone: string;
  estHours: number;
  compliancePct: number;
  assignedTeam: string;
}

export type InspectionStatus = 'Scheduled' | 'In Progress' | 'Passed' | 'Failed';
export type InspectionResult = 'Pass' | 'Fail' | 'N/A' | 'Pending';
export interface InspectionItem { label: string; result: InspectionResult; note?: string }
export interface Inspection {
  id: string;
  title: string;
  assetId: string;
  assetName: string;
  template: string;
  status: InspectionStatus;
  dueDate: string;
  inspector: string;
  items: InspectionItem[];
}

// ── Inventory & Parts ─────────────────────────────────────────────────────────
export type AbcClass = 'A' | 'B' | 'C';
export interface Part {
  id: string;
  sku: string;
  name: string;
  category: string;
  onHand: number;
  reorderPoint: number;
  unitCost: number;
  warehouseId: string;
  bin: string;
  abcClass: AbcClass;
  supplierId: string;
  leadTimeDays: number;
}

export interface Warehouse {
  id: string;
  name: string;
  location: string;
  binCount: number;
  skuCount: number;
  valueUsd: number;
}

export interface Supplier {
  id: string;
  name: string;
  category: string;
  leadTimeDays: number;
  rating: number; // 0-5
  contact: string;
  onTimePct: number;
}

export type PoStatus = 'Draft' | 'Approved' | 'Sent' | 'Received' | 'Cancelled';
export interface PoLine { sku: string; name: string; qty: number; unitCost: number }
export interface PurchaseOrder {
  id: string;
  supplierId: string;
  supplierName: string;
  status: PoStatus;
  createdAt: string;
  expectedAt: string;
  total: number;
  lines: PoLine[];
}

// ── AI / MLOps ────────────────────────────────────────────────────────────────
export type ModelStatus = 'Production' | 'Staging' | 'Shadow' | 'Retired';
export interface ModelVersion {
  version: string;
  trainedAt: string;
  accuracy: number;
  status: ModelStatus;
  notes: string;
}
export interface FeatureImportance { feature: string; importance: number } // 0-1
export interface Model {
  id: string;
  name: string;
  task: string;
  status: ModelStatus;
  version: string;
  accuracy: number;   // 0-100
  driftPct: number;   // population stability index proxy, 0-100
  lastTrained: string;
  owner: string;
  framework: string;
  predictionsPerDay: number;
  features: FeatureImportance[];
  versions: ModelVersion[];
}

export interface ForecastPoint {
  label: string;
  actual?: number;   // history
  forecast: number;  // predicted
  lower: number;     // confidence band
  upper: number;
}
export interface ForecastSeries {
  id: string;
  name: string;
  unit: string;
  points: ForecastPoint[];
}

export type AnomalySeverity = 'Critical' | 'Warning' | 'Info';
export interface AnomalyEvent {
  id: string;
  assetId: string;
  assetName: string;
  metric: string;
  severity: AnomalySeverity;
  detectedAt: string;
  description: string;
  zScore: number;
  confidence: number; // 0-100
}

// ── Analytics & Reporting ─────────────────────────────────────────────────────
export interface Report {
  id: string;
  name: string;
  category: string;   // Executive / Financial / Maintenance / Utilization / Compliance / AI
  persona: string;
  description: string;
  format: string;     // PDF / Excel / Dashboard
  lastRun: string;
  metrics: string[];
  scheduled?: boolean;
}

// ── Alerts & Notifications ────────────────────────────────────────────────────
export type AlertStatus = 'Open' | 'Acknowledged' | 'Escalated' | 'Resolved';
export interface Alert {
  id: string;
  title: string;
  severity: 'Critical' | 'Warning' | 'Info';
  type: string;
  assetId?: string;
  assetName?: string;
  status: AlertStatus;
  createdAt: string;
  source: string;
}
export interface AlertRule {
  id: string;
  name: string;
  condition: string;
  severity: 'Critical' | 'Warning' | 'Info';
  channels: string[];
  enabled: boolean;
  triggered24h: number;
}
export interface Notification {
  id: string;
  title: string;
  body: string;
  category: string;
  read: boolean;
  at: string;
}

// ── Compliance & Audit ────────────────────────────────────────────────────────
export interface AuditRecord {
  id: string;
  actor: string;
  action: string;
  target: string;
  category: string;
  timestamp: string;
  ip: string;
}
export type CycleCountStatus = 'Scheduled' | 'In Progress' | 'Reconciled' | 'Variance';
export interface CycleCount {
  id: string;
  location: string;
  status: CycleCountStatus;
  counted: number;
  expected: number;
  date: string;
  assignedTo: string;
}
export type CertStatus = 'Valid' | 'Expiring' | 'Expired';
export interface Certification {
  id: string;
  assetId: string;
  assetName: string;
  name: string;
  authority: string;
  issuedAt: string;
  expiresAt: string;
  status: CertStatus;
}
export type CustodyAction = 'Assigned' | 'Checked Out' | 'Checked In' | 'Transferred';
export interface CustodyRecord {
  id: string;
  assetId: string;
  assetName: string;
  holder: string;
  action: CustodyAction;
  at: string;
  by: string;
}

// ── Administration & Platform ─────────────────────────────────────────────────
export type IntegrationStatus = 'Connected' | 'Disconnected' | 'Error';
export interface Integration {
  id: string;
  name: string;
  category: string;
  status: IntegrationStatus;
  lastSync: string;
  description: string;
}
export interface WorkflowStep { name: string; approver: string }
export interface ApprovalWorkflow {
  id: string;
  name: string;
  trigger: string;
  steps: WorkflowStep[];
  status: 'Active' | 'Draft';
}
